# .github/workflows/workflow.yml
name: CI

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Rust toolchain
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
            profile: minimal
            toolchain: stable
            override: true

      # run sccache
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.7

      # Check code formatting
      - name: Check formatting
        run: cargo fmt --all --check
      
      # Run Clippy (linting)
      - name: Run Clippy
        run: cargo clippy --all-targets -- -D warnings


      # Run tests with cargo-nextest
      - name: Run Tests
        run: cargo test